Repository ijlee2/ember-container-query, pull requests merged in 2021-12, with the labels that each got.

#99 Replaced custom caching strategy with one built into @actions/setup-node
  .github/workflows/ci.yml
  config/ember-try.js
  package.json
Labels: enhance: documentation

#100 Updated development dependencies to their latest version
  package.json
  tests/dummy/config/ember-cli-update.json
  yarn.lock
Labels: enhance: dependency

#74 Replaced ember-did-resize-modifier with ember-on-resize-modifier
  addon/components/container-query.hbs
  addon/components/container-query.js
  package.json
  tests/dummy/app/components/widgets/widget-2/stacked-chart.hbs
  tests/dummy/app/components/widgets/widget-2/stacked-chart.js
  yarn.lock
Labels: enhance: dependency

#103 Applied timeout to all rendering and application tests
  tests/acceptance/album/accessibility-test.js
  tests/acceptance/album/visual-regression-test.js
  tests/acceptance/dashboard/accessibility-test.js
  tests/acceptance/dashboard/visual-regression-test.js
  tests/acceptance/form/accessibility-test.js
  tests/acceptance/form/visual-regression-test.js
  tests/acceptance/index/accessibility-test.js
  tests/acceptance/not-found/accessibility-test.js
  tests/helpers/resize-container.js
  tests/integration/components/container-query/dataAttributePrefix-test.js
  tests/integration/components/container-query/debounce-test.js
  tests/integration/components/container-query/features-test.js
  tests/integration/components/container-query/splattributes-test.js
  tests/integration/components/container-query/tagName-test.js
Labels: enhance: documentation

#102 Removed @percy/exec-action (deprecated)
  .github/workflows/ci.yml
  CONTRIBUTING.md
  package.json
Labels: enhance: documentation

#104 Updated style and tests for demo app
  tests/acceptance/album/visual-regression-test.js
  tests/dummy/app/components/form.css
  tests/dummy/app/components/form.hbs
  tests/dummy/app/components/navigation-menu.css
  tests/dummy/app/components/navigation-menu.hbs
  tests/dummy/app/components/navigation-menu.js
  tests/dummy/app/components/widgets/widget-1.hbs
  tests/dummy/app/components/widgets/widget-1/item.hbs
  tests/dummy/app/styles/album.css
  tests/dummy/app/styles/dashboard.css
  tests/dummy/app/styles/form.css
  tests/dummy/app/styles/not-found.css
  tests/dummy/app/templates/application.hbs
  tests/integration/components/container-query/tagName-test.js
  tests/integration/components/form/information-test.js
  tests/integration/components/navigation-menu-test.js
  tests/integration/components/widgets/widget-1-test.js
  tests/integration/components/widgets/widget-2-test.js
  tests/integration/components/widgets/widget-3-test.js
  tests/integration/components/widgets/widget-4-test.js
  tests/integration/components/widgets/widget-5-test.js
Labels: enhance: documentation

#106 Dropped support for 3.20 LTS
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking
