Repository ijlee2/ember-container-query, pull requests merged in 2023-04, with the labels that each got.

#169 Updated development dependencies. Patched unused and missing styles.
  .prettierignore
  .prettierrc.js
  docs-app/app/components/navigation-menu.hbs
  docs-app/app/components/tracks/table.hbs
  docs-app/app/components/ui/page.hbs
  docs-app/app/components/widgets/widget-1.hbs
  docs-app/app/styles/dashboard.css
  docs-app/app/styles/products.css
  docs-app/package.json
  ember-container-query/package.json
  package.json
  test-app/package.json
  yarn.lock
Labels: enhance: dependency

#170 Updated TypeScript syntax
  docs-app/.eslintrc.js
  docs-app/app/components/navigation-menu.ts
  docs-app/app/components/tracks.ts
  docs-app/app/components/tracks/list.ts
  docs-app/app/components/tracks/table.ts
  docs-app/app/components/ui/form/information.ts
  docs-app/app/components/ui/page.ts
  docs-app/app/components/widgets/widget-2.ts
  docs-app/app/components/widgets/widget-2/captions.ts
  docs-app/app/components/widgets/widget-2/stacked-chart.ts
  docs-app/app/components/widgets/widget-3.ts
  docs-app/app/components/widgets/widget-3/tour-schedule.ts
  docs-app/app/components/widgets/widget-3/tour-schedule/responsive-image.ts
  docs-app/app/components/widgets/widget-4/memo/actions.ts
  docs-app/app/components/widgets/widget-4/memo/body.ts
  docs-app/app/components/widgets/widget-4/memo/header.ts
  docs-app/app/data/album.ts
  docs-app/app/data/concert.ts
  docs-app/app/data/music-revenue.ts
  docs-app/app/helpers/add.ts
  docs-app/app/modifiers/draw-stacked-chart.d.ts
  docs-app/app/utils/components/widgets/widget-2.ts
  docs-app/app/utils/components/widgets/widget-3.ts
  docs-app/tests/helpers/percy.ts
  docs-app/tests/integration/components/tracks/list-test.ts
  docs-app/tests/integration/components/tracks/table-test.ts
  ember-container-query/.eslintrc.js
  ember-container-query/src/modifiers/container-query.ts
  test-app/.eslintrc.js
Labels: enhance: documentation

#171 Renamed component signatures
  docs-app/app/components/navigation-menu.ts
  docs-app/app/components/products/product/card.ts
  docs-app/app/components/products/product/image.ts
  docs-app/app/components/tracks.ts
  docs-app/app/components/tracks/list.ts
  docs-app/app/components/tracks/table.ts
  docs-app/app/components/ui/form.ts
  docs-app/app/components/ui/form/checkbox.ts
  docs-app/app/components/ui/form/field.ts
  docs-app/app/components/ui/form/information.ts
  docs-app/app/components/ui/form/input.ts
  docs-app/app/components/ui/form/textarea.ts
  docs-app/app/components/ui/page.ts
  docs-app/app/components/widgets/widget-1.ts
  docs-app/app/components/widgets/widget-1/item.ts
  docs-app/app/components/widgets/widget-2.ts
  docs-app/app/components/widgets/widget-2/captions.ts
  docs-app/app/components/widgets/widget-2/stacked-chart.ts
  docs-app/app/components/widgets/widget-3.ts
  docs-app/app/components/widgets/widget-3/tour-schedule.ts
  docs-app/app/components/widgets/widget-3/tour-schedule/responsive-image.ts
  docs-app/app/components/widgets/widget-4.ts
  docs-app/app/components/widgets/widget-4/memo.ts
  docs-app/app/components/widgets/widget-4/memo/actions.ts
  docs-app/app/components/widgets/widget-4/memo/body.ts
  docs-app/app/components/widgets/widget-4/memo/header.ts
  docs-app/app/components/widgets/widget-5.ts
  ember-container-query/src/components/container-query.ts
Labels: enhance: documentation

#172 Updated ember-source to v4.12.0
  docs-app/.eslintrc.js
  docs-app/.stylelintignore
  docs-app/.stylelintrc.js
  docs-app/app/components/products/product/card.css
  docs-app/app/components/products/product/image.css
  docs-app/app/components/ui/form/field.css
  docs-app/app/components/ui/page.css
  docs-app/app/components/widgets/widget-1.css
  docs-app/app/components/widgets/widget-1/item.css
  docs-app/app/components/widgets/widget-2/captions.css
  docs-app/app/components/widgets/widget-2/stacked-chart.css
  docs-app/app/components/widgets/widget-3/tour-schedule.css
  docs-app/app/components/widgets/widget-4.css
  docs-app/app/components/widgets/widget-4/memo.css
  docs-app/app/components/widgets/widget-4/memo/body.css
  docs-app/app/components/widgets/widget-4/memo/header.css
  docs-app/app/controllers/album.ts
  docs-app/app/controllers/products.ts
  docs-app/app/routes/products.ts
  docs-app/app/styles/album.css
  docs-app/app/styles/application.css
  docs-app/app/styles/dashboard.css
  docs-app/app/styles/not-found.css
  docs-app/app/styles/products.css
  docs-app/config/ember-cli-update.json
  docs-app/package.json
  ember-container-query/package.json
  test-app/.eslintrc.js
  test-app/app/styles/app.css
  test-app/config/ember-cli-update.json
  test-app/package.json
  yarn.lock
Labels: enhance: dependency

#168 fix(docs): only process own styles as local
  docs-app/ember-cli-build.js
Labels: enhance: dependency

#173 Set up ember-template-imports
  .gitattributes
  docs-app/.eslintrc.js
  docs-app/.prettierignore
  docs-app/.template-lintrc.js
  docs-app/app/components/navigation-menu.gts
  docs-app/app/components/navigation-menu.hbs
  docs-app/app/components/navigation-menu.ts
  docs-app/package.json
  docs-app/tests/integration/components/navigation-menu-test.gts
  docs-app/tsconfig.json
  docs-app/types/test-app/index.d.ts
  ember-container-query/package.json
  test-app/package.json
  yarn.lock
Labels: enhance: documentation

#175 Updated configuration files to match Ember v4.12 blueprint
  .gitignore
  docs-app/.ember-cli
  docs-app/.eslintignore
  docs-app/.gitignore
  docs-app/.prettierignore
  docs-app/.watchmanconfig
  ember-container-query/.eslintignore
  ember-container-query/.eslintrc.js
  ember-container-query/.gitignore
  ember-container-query/.prettierignore
  test-app/.ember-cli
  test-app/.eslintignore
  test-app/.gitignore
  test-app/.prettierignore
  test-app/.watchmanconfig
Labels: enhance: dependency

#177 Updated README
  README.md
  ember-container-query/package.json
Labels: enhance: documentation

#178 Reexported types from modifiers/container-query.ts in index.ts
  README.md
  docs-app/app/components/widgets/widget-3/tour-schedule/responsive-image.ts
  ember-container-query/README.md
  ember-container-query/src/index.ts
  test-app/tests/integration/components/container-query/features-test.ts
Labels: enhance: code

#179 Add examples of <template>-tag components
  docs-app/app/components/tracks.hbs
  docs-app/app/components/tracks/list.hbs
  docs-app/app/components/tracks/table.gts
  docs-app/app/components/tracks/table.hbs
  docs-app/app/components/tracks/table.ts
  docs-app/app/components/ui/form.hbs
  docs-app/app/components/ui/form/checkbox.hbs
  docs-app/app/components/ui/form/field.hbs
  docs-app/app/components/ui/form/information.hbs
  docs-app/app/components/ui/form/input.hbs
  docs-app/app/components/ui/form/textarea.hbs
  docs-app/app/components/widgets/widget-1.gts
  docs-app/app/components/widgets/widget-1.hbs
  docs-app/app/components/widgets/widget-1.ts
  docs-app/app/components/widgets/widget-1/item.gts
  docs-app/app/components/widgets/widget-1/item.hbs
  docs-app/app/components/widgets/widget-1/item.ts
  docs-app/app/components/widgets/widget-2/captions.hbs
  docs-app/app/components/widgets/widget-2/captions.ts
  docs-app/app/components/widgets/widget-2/stacked-chart.gts
  docs-app/app/components/widgets/widget-2/stacked-chart.hbs
  docs-app/app/components/widgets/widget-2/stacked-chart.ts
  docs-app/app/components/widgets/widget-3/tour-schedule.gts
  docs-app/app/components/widgets/widget-3/tour-schedule.hbs
  docs-app/app/components/widgets/widget-3/tour-schedule.ts
  docs-app/app/components/widgets/widget-3/tour-schedule/responsive-image.gts
  docs-app/app/components/widgets/widget-3/tour-schedule/responsive-image.hbs
  docs-app/app/components/widgets/widget-4.gts
  docs-app/app/components/widgets/widget-4.hbs
  docs-app/app/components/widgets/widget-4.ts
  docs-app/app/components/widgets/widget-4/memo.gts
  docs-app/app/components/widgets/widget-4/memo.hbs
  docs-app/app/components/widgets/widget-4/memo.ts
  docs-app/app/components/widgets/widget-4/memo/actions.gts
  docs-app/app/components/widgets/widget-4/memo/actions.hbs
  docs-app/app/components/widgets/widget-4/memo/actions.ts
  docs-app/app/components/widgets/widget-4/memo/body.gts
  docs-app/app/components/widgets/widget-4/memo/body.hbs
  docs-app/app/components/widgets/widget-4/memo/body.ts
  docs-app/app/components/widgets/widget-4/memo/header.gts
  docs-app/app/components/widgets/widget-4/memo/header.hbs
  docs-app/app/components/widgets/widget-4/memo/header.ts
  docs-app/app/components/widgets/widget-5.gts
  docs-app/app/components/widgets/widget-5.hbs
  docs-app/app/components/widgets/widget-5.ts
  docs-app/app/helpers/strict-and.ts
  docs-app/app/helpers/strict-or.ts
  docs-app/app/templates/album.hbs
  docs-app/package.json
  docs-app/tests/acceptance/dashboard/visual-regression-test.ts
  docs-app/tests/integration/helpers/strict-and-test.ts
  docs-app/tests/integration/helpers/strict-or-test.ts
  docs-app/types/test-app/index.d.ts
  yarn.lock
Labels: enhance: documentation

#183 Updated <Products::Product::Card> to be a template-only component
  docs-app/app/components/products/product/card.gts
  docs-app/app/components/products/product/card.hbs
  docs-app/app/components/products/product/card.ts
Labels: enhance: documentation

#184 Updated <Ui::Form::Field> to be a <template>-tag component
  docs-app/app/components/ui/form/field.gts
  docs-app/app/components/ui/form/field.hbs
  docs-app/app/components/ui/form/field.ts
Labels: enhance: documentation

#185 Updated development dependencies and CONTRIBUTING.md
  .gitignore
  CONTRIBUTING.md
  docs-app/.prettierrc.js
  docs-app/app/components/products/product/card.css
  docs-app/app/components/ui/form.ts
  docs-app/app/components/ui/form/field.css
  docs-app/app/components/ui/page.css
  docs-app/app/components/widgets/widget-1.css
  docs-app/app/components/widgets/widget-2/captions.css
  docs-app/app/components/widgets/widget-3/tour-schedule.css
  docs-app/app/components/widgets/widget-4.css
  docs-app/app/components/widgets/widget-4/memo/header.css
  docs-app/app/controllers/album.css
  docs-app/app/controllers/application.css
  docs-app/app/controllers/dashboard.css
  docs-app/app/controllers/products.css
  docs-app/app/modifiers/draw-stacked-chart.js
  docs-app/app/modifiers/dynamic-css-grid.ts
  docs-app/app/utils/components/widgets/widget-2.ts
  docs-app/app/utils/components/widgets/widget-3.ts
  docs-app/package.json
  docs-app/tests/acceptance/album/visual-regression-test.ts
  docs-app/tests/acceptance/dashboard/visual-regression-test.ts
  docs-app/tests/helpers/index.ts
  docs-app/tests/helpers/percy.ts
  docs-app/tests/helpers/reset-viewport.ts
  docs-app/tests/helpers/resize-container.ts
  docs-app/tests/integration/components/products/product/card-test.ts
  docs-app/tests/integration/components/tracks-test.ts
  docs-app/tests/integration/components/tracks/list-test.ts
  docs-app/tests/integration/components/tracks/table-test.ts
  docs-app/tests/integration/components/ui/form-test.ts
  docs-app/tests/integration/components/ui/form/checkbox-test.ts
  docs-app/tests/integration/components/ui/form/information-test.ts
  docs-app/tests/integration/components/ui/form/input-test.ts
  docs-app/tests/integration/components/ui/form/textarea-test.ts
  docs-app/tests/integration/components/widgets/widget-5-test.ts
  docs-app/tests/unit/utils/components/widgets/widget-2-test.ts
  docs-app/tests/unit/utils/components/widgets/widget-3-test.ts
  ember-container-query/.prettierrc.js
  ember-container-query/package.json
  ember-container-query/src/components/container-query.ts
  ember-container-query/src/helpers/aspect-ratio.ts
  ember-container-query/src/modifiers/container-query.ts
  test-app/.prettierrc.js
  test-app/package.json
  test-app/tests/helpers/container-query.ts
  test-app/tests/helpers/index.ts
  test-app/tests/helpers/resize-container.ts
  test-app/tests/integration/components/container-query/dataAttributePrefix-test.ts
  yarn.lock
Labels: enhance: documentation, enhance: dependency

#186 Sync apps with those from embroider-css-modules
  docs-app/.stylelintrc.js
  docs-app/app/components/navigation-menu.gts
  docs-app/app/components/products/product/card.gts
  docs-app/app/components/products/product/image.gts
  docs-app/app/components/tracks/list.hbs
  docs-app/app/components/tracks/table.gts
  docs-app/app/components/ui/form.hbs
  docs-app/app/components/ui/form.ts
  docs-app/app/components/ui/form/checkbox.hbs
  docs-app/app/components/ui/form/field.gts
  docs-app/app/components/ui/form/information.gts
  docs-app/app/components/ui/form/input.hbs
  docs-app/app/components/ui/form/textarea.hbs
  docs-app/app/components/ui/page.gts
  docs-app/app/components/widgets/widget-2.hbs
  docs-app/app/components/widgets/widget-2/captions.hbs
  docs-app/app/components/widgets/widget-3.hbs
  docs-app/app/components/widgets/widget-3/tour-schedule.gts
  docs-app/app/components/widgets/widget-3/tour-schedule/responsive-image.gts
  docs-app/app/components/widgets/widget-4/memo/actions.gts
  docs-app/app/components/widgets/widget-4/memo/body.gts
  docs-app/app/components/widgets/widget-4/memo/header.gts
  docs-app/app/components/widgets/widget-5.gts
  docs-app/app/controllers/products.css
  docs-app/app/controllers/products.css.d.ts
  docs-app/app/controllers/products.ts
  docs-app/app/templates/album.hbs
  docs-app/app/templates/application.hbs
  docs-app/app/templates/dashboard.hbs
  docs-app/app/templates/index.hbs
  docs-app/app/templates/not-found.hbs
  docs-app/app/templates/products.hbs
  docs-app/package.json
  docs-app/postcss.config.js
  docs-app/tests/acceptance/index/visual-regression-test.ts
  docs-app/tests/helpers/index.ts
  docs-app/tests/integration/components/navigation-menu-test.gts
  docs-app/tests/test-helper.ts
  test-app/.eslintrc.js
  test-app/.prettierignore
  test-app/.prettierrc.js
  test-app/.template-lintrc.js
  test-app/tests/helpers/index.ts
  test-app/tests/test-helper.ts
  yarn.lock
Labels: enhance: documentation
